apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 97-dhcp-master
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
      - contents:
          source: data:,%5Bmain%5D%0Ano-auto-default%3D*%0A
        filesystem: root
        mode: 420
        path: /etc/NetworkManager/conf.d/10-dhcp-config.conf
