apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: load-mpls-module
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,bXBsc19pcHR1bm5lbAptcGxzX3JvdXRlcgppcF90dW5uZWwK
        overwrite: true
        filesystem: root
        mode: 420
        path: /etc/modules-load.d/mpls-load.conf
