apiVersion: tuned.openshift.io/v1
kind: Tuned
metadata:
  name: set-powersave
  namespace: openshift-cluster-node-tuning-operator
spec:
  profile:
  - name: powersave
    data: |
      [cpu]
      governor=powersave
  recommend:
  - priority: 10
    profile: powersave
