---
apiVersion: v1
kind: Namespace
metadata:
  name: bind-ns
  labels:
    pod-security.kubernetes.io/enforce: "restricted"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bind-pvc
  namespace: bind-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: lvms-vg1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bind-config
  namespace: bind-ns
data:
  named.conf: |
    include "/etc/bind/zones.conf";
  zones.conf: |
    zone "infra.5g-deployment.lab" {
      type master;
      file "/etc/bind/zones/infra.zone";
      allow-update { any; };
    };

    zone "api.hub.5g-deployment.lab" {
      type master;
      file "/etc/bind/zones/api.zone";
      allow-update { any; };
    };
  infra.zone: |
    $TTL 1h
    @   IN  SOA ns1.infra.5g-deployment.lab. admin.5g-deployment.lab. (
        2025080801 ; Serial
        1h         ; Refresh
        15m        ; Retry
        1w         ; Expire
        1h )       ; Negative Cache TTL
    @   IN  NS  ns1.infra.5g-deployment.lab.
    ns1 IN  A   10.0.0.53
  api.zone: |
    $TTL 1h
    @   IN  SOA ns1.api.hub.5g-deployment.lab. admin.5g-deployment.lab. (
        2025080801 ; Serial
        1h         ; Refresh
        15m        ; Retry
        1w         ; Expire
        1h )       ; Negative Cache TTL
    @   IN  NS  ns1.api.hub.5g-deployment.lab.
    ns1 IN  A   10.0.0.53
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind
  namespace: bind-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bind
  template:
    metadata:
      labels:
        app: bind
    spec:
      securityContext:
        runAsUser: 0
        runAsNonRoot: false
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: bind
          image: quay.io/midu/bind:fedora-latest
          ports:
            - containerPort: 53
              protocol: UDP
            - containerPort: 53
              protocol: TCP
          args:
            - "named"
            - "-g"
            - "-c"
            - "/etc/bind/named.conf"
          volumeMounts:
            - name: bind-config
              mountPath: /etc/bind/
            - name: bind-cache
              mountPath: /var/cache/bind
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
      volumes:
        - name: bind-config
          configMap:
            name: bind-config
            items:
              - key: named.conf
                path: named.conf
              - key: zones.conf
                path: zones.conf
              - key: infra.zone
                path: zones/infra.zone
              - key: api.zone
                path: zones/api.zone
        - name: bind-cache
          persistentVolumeClaim:
            claimName: bind-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: bind-service
  namespace: bind-ns
spec:
  type: NodePort
  selector:
    app: bind
  ports:
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
      nodePort: 30053
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
      nodePort: 30054
